spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
        - id: hello-service
          uri: http://localhost:9000
          predicates:
          - Path=/hello-service/**
          filters:
           - RewritePath=/hello-service/(?<path>.*), /$\{path}
server:
  port: 8082
